name: gnnbc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - autograd=1.3=py_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.4.5.1=py37_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.12=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0.2=ha0c5888_2
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_1005
  - freetype=2.9.1=h8a8886c_1
  - future=0.18.2=py37_0
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.5.19=h2a4e5f8_1
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hc401514_3
  - icu=58.2=h9c2bf20_1
  - imageio=2.8.0=py_0
  - intel-openmp=2019.4=243
  - jasper=2.0.14=h07fcdf6_1
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py37he6710b0_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1000
  - libiconv=1.15=h516909a_1005
  - libopencv=3.4.2=hb342d67_1
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.1=py37h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.3=0
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1g=h7b6447c_0
  - pandas=1.0.3=py37h0573a6f_0
  - pcre=8.43=he6710b0_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h516909a_1003
  - py-opencv=3.4.2=py37hb342d67_1
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyqtgraph=0.10.0=py37h28b3542_3
  - python=3.7.6=h0371630_2
  - python-dateutil=2.8.1=py_0
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2019.3=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.22.1=py37hd81dba3_0
  - scipy=1.3.2=py37h7c811a0_0
  - seaborn=0.10.0=py_0
  - setuptools=44.0.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.5.0=py37_cu101
  - tornado=6.0.3=py37h7b6447c_0
  - tqdm=4.43.0=py_0
  - wheel=0.33.6=py37_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.0
    - cloudpickle==1.3.0
    - decorator==4.4.1
    - defusedxml==0.6.0
    - entrypoints==0.3
    - graph_nets==1.1.0
    - gym==0.17.1
    - importlib-metadata==1.5.0
    - ipykernel==5.1.4
    - ipython==7.12.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.16.0
    - jinja2==2.11.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==5.3.4
    - jupyter-console==6.1.0
    - jupyter-core==4.6.1
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.4
    - networkx==2.4
    - notebook==6.0.3
    - pandocfilters==1.4.2
    - parso==0.6.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.3
    - ptyprocess==0.6.0
    - pydoe==0.3.8
    - pyglet==1.5.0
    - pygments==2.5.2
    - pyrsistent==0.15.7
    - pyzmq==18.1.1
    - qtconsole==4.6.0
    - scipy==1.4.1
    - send2trash==1.5.0
    - terminado==0.8.3
    - testpath==0.4.4
    - traitlets==4.3.3
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==2.2.0
prefix: /home/vinayksk/anaconda3/envs/gnnbc

